imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UsersBundle/Resources/config/services.yml" }
    - { resource: "@LayoutBundle/Resources/config/services.yml" }
    - { resource: "@BackEndBundle/Resources/config/services.yml" }
    - { resource: "@FrontEndBundle/Resources/config/services.yml" }
    - { resource: "@EntitasBundle/Resources/config/services.yml" }
    - { resource: "@DocBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UsersBundle\Entity\User
    from_email:
        address: pmkl@gmail.com
        sender_name: PMKL

hwi_oauth:
    firewall_names: [main]
    http_client:
        timeout:       10
    connect:
        confirmation: true
    resource_owners:
        facebook:
            type:                facebook
            client_id:           703414113093857
            client_secret:       d5ccb1eb0c50486e1fb5ede32521c714
            scope:               "email"
        google:
            type:                google
            client_id:           7ae34d0bf8ae25f83949
            client_secret:       762dffcce4d24e8103df6e5546fa7612fe7647af
            scope:               "user:email"
        twitter:
            type:                twitter
            client_id:           703414113093857
            client_secret:       d5ccb1eb0c50486e1fb5ede32521c714
            scope:               "email"
        linkedin:
            type:                linkedin
            client_id:           703414113093857
            client_secret:       d5ccb1eb0c50486e1fb5ede32521c714
            scope:               "email"   
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookID
            google: googleID
            twitter: twitterID
            linkedin: linkedinID

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: true
    default_renderer: twig
    providers:
        builder_alias: false 
        container_aware: true

knp_paginator:
    page_range: 15                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig 
        # pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        pagination: pagination.html.twig

# knp_snappy:
#     pdf:
#         enabled:    true
#         binary:     "%kernel.root_dir%/../bin/wkhtmltopdf"
#         options:    []

#This Setting For Local In Windows
knp_snappy:
    pdf:
        enabled:    true
        binary: "\"C:/Program Files (x86)/wkhtmltopdf/bin/wkhtmltopdf.exe\""
        options:    []
        
liip_imagine:
    filter_sets:
        cache: ~
        anggota_thumb:
            quality: 100
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        anggota_front:
            quality: 100
            filters:
                thumbnail: { size: [240, 240], mode: outbound }
                background : { size : [242, 242], position : center, color : '#ffffff' }
        logo_thumb:
            quality: 100
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
                background : { size : [152, 152], position : center, color : '#ffffff' }

vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix:         /adminlte/anggota_pic
            upload_destination: %kernel.root_dir%/../web/adminlte/anggota_pic

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        logoorg_image:
            uri_prefix:         /adminlte/logoorg_pic
            upload_destination: %kernel.root_dir%/../web/adminlte/logoorg_pic

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true