forumcontent_index:
    path:     /
    defaults: { _controller: "EntitasBundle:ForumContent:index" }
    methods:  GET

forumcontent_show:
    path:     /{id}/show
    defaults: { _controller: "EntitasBundle:ForumContent:show" }
    methods:  GET

forumcontent_new:
    path:     /new
    defaults: { _controller: "EntitasBundle:ForumContent:new" }
    methods:  [GET, POST]

forumcontent_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntitasBundle:ForumContent:edit" }
    methods:  [GET, POST]
    options:
            expose: true
forumcontent_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntitasBundle:ForumContent:delete" }
    methods:  DELETE
