foslogoorg_index:
    path:     /
    defaults: { _controller: "EntitasBundle:FosLogoorg:index" }
    methods:  GET

foslogoorg_show:
    path:     /{id}/show
    defaults: { _controller: "EntitasBundle:FosLogoorg:show" }
    methods:  GET

foslogoorg_new:
    path:     /new
    defaults: { _controller: "EntitasBundle:FosLogoorg:new" }
    methods:  [GET, POST]

foslogoorg_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntitasBundle:FosLogoorg:edit" }
    methods:  [GET, POST]
    options:
            expose: true

foslogoorg_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntitasBundle:FosLogoorg:delete" }
    methods:  DELETE
