fostypepengeluaran_index:
    path:     /
    defaults: { _controller: "EntitasBundle:FosTypepengeluaran:index" }
    methods:  GET

fostypepengeluaran_show:
    path:     /{id}/show
    defaults: { _controller: "EntitasBundle:FosTypepengeluaran:show" }
    methods:  GET

fostypepengeluaran_new:
    path:     /new
    defaults: { _controller: "EntitasBundle:FosTypepengeluaran:new" }
    methods:  [GET, POST]

fostypepengeluaran_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntitasBundle:FosTypepengeluaran:edit" }
    methods:  [GET, POST]
    options:
            expose: true

fostypepengeluaran_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntitasBundle:FosTypepengeluaran:delete" }
    methods:  DELETE
