fostypependidikan_index:
    path:     /
    defaults: { _controller: "EntitasBundle:FosTypependidikan:index" }
    methods:  GET

fostypependidikan_show:
    path:     /{id}/show
    defaults: { _controller: "EntitasBundle:FosTypependidikan:show" }
    methods:  GET

fostypependidikan_new:
    path:     /new
    defaults: { _controller: "EntitasBundle:FosTypependidikan:new" }
    methods:  [GET, POST]

fostypependidikan_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntitasBundle:FosTypependidikan:edit" }
    methods:  [GET, POST]
    options:
            expose: true

fostypependidikan_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntitasBundle:FosTypependidikan:delete" }
    methods:  DELETE
