<?php

namespace EntitasBundle\Repositories;

/**
 * DendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FosStrukorgRepository extends \Doctrine\ORM\EntityRepository
{
        
        public function findAllArray()
        {
			$query = $this->getEntityManager()
			        		->createQuery('
			        						SELECT mt.id as key,c.namaType as title,
			        						(CASE WHEN pTj.id IS NULL THEN 0 ELSE pTj.id END) as parent,
			        						(
			        							CASE WHEN mt.isAssistant = 1 
			        							THEN 
			        								true
		        								ELSE 
		        									false 
	        									END
        									)as isAssistant,
			        						prof.namaLengkap as name,prof.imageName as gambar,
			        						prof.id as profileid
			        						FROM EntitasBundle:FosStrukorg mt
			        						LEFT JOIN mt.parentTypejabatan pTj
			        						INNER JOIN mt.typeJabatans c
			        						INNER JOIN mt.pjJabatan prof
			        						

										  ')
			        		->getArrayResult();
			return $query;            
        }
}