entitas_kelamin:
    resource: "@EntitasBundle/Resources/config/routing/foskelamin.yml"
    prefix:   /kelamin
entitas_profile:
    resource: "@EntitasBundle/Resources/config/routing/fosprofile.yml"
    prefix:   /profile

entitas_strukorg:
    resource: "@EntitasBundle/Resources/config/routing/fosstrukorg.yml"
    prefix:   /strukorg

entitas_logoorg:
    resource: "@EntitasBundle/Resources/config/routing/foslogoorg.yml"
    prefix:   /logoorg

entitas_profileorg:
  resource: "@EntitasBundle/Resources/config/routing/fosprofileorg.yml"
  prefix:   /profileorg

entitas_typepemasukan:
    resource: "@EntitasBundle/Resources/config/routing/fostypepemasukan.yml"
    prefix:   /typepemasukan

entitas_typepengeluaran:
  resource: "@EntitasBundle/Resources/config/routing/fostypepengeluaran.yml"
  prefix:   /typepengeluaran

entitas_typeanggota:
  resource: "@EntitasBundle/Resources/config/routing/fostypeanggota.yml"
  prefix:   /typeanggota

entitas_typejabatan:
  resource: "@EntitasBundle/Resources/config/routing/fostypejabatan.yml"
  prefix:   /typejabatan

entitas_typependidikan:
  resource: "@EntitasBundle/Resources/config/routing/fostypependidikan.yml"
  prefix:   /typependidikan

entitas_forumcategory:
  resource: "@EntitasBundle/Resources/config/routing/forumcategory.yml"
  prefix:   /forumcategory

entitas_forumstatus:
  resource: "@EntitasBundle/Resources/config/routing/forumstatus.yml"
  prefix:   /forumstatus

entitas_forumcontent:
  resource: "@EntitasBundle/Resources/config/routing/forumcontent.yml"
  prefix:   /forumcontent

entitas_forumkomentar:
  resource: "@EntitasBundle/Resources/config/routing/forumkomentar.yml"
  prefix:   /forumkomentar

entitas_forumpengumuman:
  resource: "@EntitasBundle/Resources/config/routing/forumpengumuman.yml"
  prefix:   /forumpengumuman

entitas_slider:
  resource: "@EntitasBundle/Resources/config/routing/fosslider.yml"
  prefix:   /slider

entitas_pemasukan:
  resource: "@EntitasBundle/Resources/config/routing/tblpemasukan.yml"
  prefix:   /tblpemasukan

entitas_pengeluaran:
  resource: "@EntitasBundle/Resources/config/routing/tblpengeluaran.yml"
  prefix:   /tblpengeluaran

entitas_namakegiatan:
  resource: "@EntitasBundle/Resources/config/routing/namakegiatan.yml"
  prefix:   /namakegiatan