entitas_kelamin:
    resource: "@EntitasBundle/Resources/config/routing/foskelamin.yml"
    prefix:   /kelamin
entitas_profile:
    resource: "@EntitasBundle/Resources/config/routing/fosprofile.yml"
    prefix:   /profile

entitas_strukorg:
    resource: "@EntitasBundle/Resources/config/routing/fosstrukorg.yml"
    prefix:   /strukorg

entitas_logoorg:
    resource: "@EntitasBundle/Resources/config/routing/foslogoorg.yml"
    prefix:   /logoorg

entitas_profileorg:
  resource: "@EntitasBundle/Resources/config/routing/fosprofileorg.yml"
  prefix:   /profileorg

entitas_typepemasukan:
    resource: "@EntitasBundle/Resources/config/routing/fostypepemasukan.yml"
    prefix:   /typepemasukan

entitas_typepengeluaran:
  resource: "@EntitasBundle/Resources/config/routing/fostypepengeluaran.yml"
  prefix:   /typepengeluaran

entitas_typeanggota:
  resource: "@EntitasBundle/Resources/config/routing/fostypeanggota.yml"
  prefix:   /typeanggota

entitas_typejabatan:
  resource: "@EntitasBundle/Resources/config/routing/fostypejabatan.yml"
  prefix:   /typejabatan