services:
    entitas.dropbox_client:
        class: Dropbox\Client
        arguments:
            - w8156ezOtWAAAAAAAAAAFcDeFKu_4WzVJKL7uG_h9FtizczZkcbqGdCMrI3LFSPk #ini adalah token yang digenerate dari dropbox
            - xxa88x4ngihlxxe  #app key yang terdapat di drop box
    entitas.cloudinary_client:
        class: Cloudinary\Api
        arguments:
            - zetacorp #ini adalah token yang digenerate dari dropbox
            - '339535817583289' #app key yang terdapat di drop box
            - CDoDXuz-a4NeMjVHEtI7yJP4Fl4
            - true
            - false
    entitas.slugger:
        class: EntitasBundle\Utils\Slugger

    entitas.waktu:
        class: EntitasBundle\Utils\Waktu

    entitas.tanggal:
        class: EntitasBundle\Utils\Tanggal

    entitas.searchassocarray:
        class: EntitasBundle\Utils\ArraySearchAssociative

    entitas.bulkarray:
        class: EntitasBundle\Utils\ArrayBulk

    entitas.sumcolumassocarray:
        class: EntitasBundle\Utils\ArraySumColumAssoc
    
    entitas.arrayflatten:
        class: EntitasBundle\Utils\ArrayFlatten
